// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyLgJx_VIAbscqr8V0fvLHojYQOu_t3fA',
    appId: '1:498004985934:web:e4acfa41ed9169832a1b1f',
    messagingSenderId: '498004985934',
    projectId: 'flood-prediction-12',
    authDomain: 'flood-prediction-12.firebaseapp.com',
    storageBucket: 'flood-prediction-12.appspot.com',
    measurementId: 'G-KXJ3Y03R9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuDsM9hPSHVtDwe4BXc750oB4rYMePW0I',
    appId: '1:498004985934:android:66f456a2e7aae1c52a1b1f',
    messagingSenderId: '498004985934',
    projectId: 'flood-prediction-12',
    storageBucket: 'flood-prediction-12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAAO_Dca3MQz06Pg9JxkFcsDJMg762_QM',
    appId: '1:498004985934:ios:5f3d71aee17c82832a1b1f',
    messagingSenderId: '498004985934',
    projectId: 'flood-prediction-12',
    storageBucket: 'flood-prediction-12.appspot.com',
    iosBundleId: 'com.example.fyp',
  );
}
